/*
 * Copyright DataStax, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Text.Json.Serialization;

namespace DataStax.AstraDB.DataApi.Core;

/// <summary>
/// Autogenerated id types
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter<DefaultIdType>))]
public enum DefaultIdType
{
    /// <summary>
    /// MongoDB ObjectId
    /// </summary>
    [JsonStringEnumMemberName("objectId")]
    ObjectId,
    /// <summary>UUID version 6 (time-ordered).</summary>
    [JsonStringEnumMemberName("uuidv6")]
    UuidV6,
    /// <summary>UUID version 7 (time-ordered, Unix epoch based).</summary>
    [JsonStringEnumMemberName("uuidv7")]
    UuidV7,
    /// <summary>Standard UUID (version 4, random).</summary>
    [JsonStringEnumMemberName("uuid")]
    Uuid
}
