// /*
//  * Copyright DataStax, Inc.
//  *
//  * Licensed under the Apache License, Version 2.0 (the "License");
//  * you may not use this file except in compliance with the License.
//  * You may obtain a copy of the License at
//  *
//  * http://www.apache.org/licenses/LICENSE-2.0
//  *
//  * Unless required by applicable law or agreed to in writing, software
//  * distributed under the License is distributed on an "AS IS" BASIS,
//  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  * See the License for the specific language governing permissions and
//  * limitations under the License.
//  */

// using DataStax.AstraDB.DataApi.Core;
// using DataStax.AstraDB.DataApi.SerDes;
// using System;
// using System.Text.Json.Serialization;

// namespace DataStax.AstraDB.DataApi.Tables;


// /// <summary>
// /// Represents a column in a table
// /// </summary>
// [JsonConverter(typeof(ColumnConverter))]
// public class Column
// {
//     [JsonPropertyName("type")]
//     public string TypeKey { get; set; }

//     // [JsonPropertyName("type")]
//     // [JsonInclude]
//     // internal string TypeString
//     // {
//     //     get { return Type == DataApiType.None ? null : Type.ToString().ToLowerInvariant(); }
//     //     set { Type = value == null ? DataApiType.None : (DataApiType)Enum.Parse(typeof(DataApiType), value, true); }
//     // }

//     // [JsonPropertyName("keyType")]
//     // [JsonInclude]
//     // internal string KeyTypeString
//     // {
//     //     get { return KeyType == DataApiType.None ? null : KeyType.ToString().ToLowerInvariant(); }
//     //     set { KeyType = value == null ? DataApiType.None : (DataApiType)Enum.Parse(typeof(DataApiType), value, true); }
//     // }

//     // [JsonPropertyName("valueType")]
//     // [JsonInclude]
//     // internal string ValueTypeString
//     // {
//     //     get { return ValueType == DataApiType.None ? null : ValueType.ToString().ToLowerInvariant(); }
//     //     set { ValueType = value == null ? DataApiType.None : (DataApiType)Enum.Parse(typeof(DataApiType), value, true); }
//     // }

//     // /// <summary>
//     // /// The type of the column
//     // /// </summary>
//     // //[JsonIgnore]
//     // public virtual DataApiType Type { get; set; }

//     // /// <summary>
//     // /// The type of the keys in the dictionary
//     // /// </summary>
//     // //[JsonIgnore]
//     // public DataApiType KeyType { get; set; }

//     // /// <summary>
//     // /// The type of the values in the dictionary
//     // /// </summary>
//     // //[JsonIgnore]
//     // public DataApiType ValueType { get; set; }
// }


// /// <summary>
// /// A column that holds vector values
// /// </summary>
// public class VectorColumn : Column
// {
//     // /// <summary>
//     // /// Defines the column as type vector
//     // /// </summary>
//     // public override DataApiType Type => DataApiType.Vector;

//     /// <summary>
//     /// The dimension of the vector
//     /// </summary>
//     [JsonPropertyName("dimension")]
//     public int Dimension { get; set; }

//     // internal VectorColumn(int dimension)
//     // {
//     //     Dimension = dimension;
//     // }

//     // /// <summary>
//     // /// Creates a new instance of the <see cref="VectorColumn"/> class.
//     // /// </summary>
//     // public VectorColumn() { }
// }

// /// <summary>
// /// A column that holds vector values that are generated by a vectorization service
// /// </summary>
// public class VectorizeColumn : VectorColumn
// {
//     /// <summary>
//     /// The vectorization service options
//     /// </summary>
//     [JsonPropertyName("service")]
//     public VectorServiceOptions ServiceOptions { get; set; }

//     // /// <summary>
//     // /// Creates a new instance of the <see cref="VectorizeColumn"/> class with the specified dimension and service options.
//     // /// </summary>
//     // /// <param name="dimension"></param>
//     // /// <param name="serviceOptions"></param>
//     // public VectorizeColumn(int dimension, VectorServiceOptions serviceOptions) // : base(dimension)
//     // {
//     //     Dimension = d
//     //     ServiceOptions = serviceOptions;
//     // }

//     // /// <summary>
//     // /// Creates a new instance of the <see cref="VectorizeColumn"/> class with the specified service options.
//     // /// </summary>
//     // /// <param name="serviceOptions"></param>
//     // public VectorizeColumn(VectorServiceOptions serviceOptions)
//     // {
//     //     ServiceOptions = serviceOptions;
//     // }

//     // /// <summary>
//     // /// Creates a new instance of the <see cref="VectorizeColumn"/> class.
//     // /// </summary>
//     // public VectorizeColumn() { }
// }

// /// <summary>
// /// A column with a User Defined Type
// /// </summary>
// public class UserDefinedTypeColumn : Column
// {
//     [JsonPropertyName("udtName")]
//     public string UserDefinedTypeName { get; set; }

//     // /// <summary>
//     // /// Defines the column as type vector
//     // /// </summary>
//     // public override DataApiType Type => DataApiType.UserDefined;

//     // /// <summary>
//     // /// The dimension of the vector
//     // /// </summary>
//     // [JsonPropertyName("dimension")]
//     // public int Dimension { get; set; }

//     // internal VectorColumn(int dimension)
//     // {
//     //     Dimension = dimension;
//     // }

//     // /// <summary>
//     // /// Creates a new instance of the <see cref="VectorColumn"/> class.
//     // /// </summary>
//     // public VectorColumn() { }
// }

// public class ListColumn : Column
// {
//     [JsonPropertyName("udtName")]
//     public string UserDefinedTypeName { get; set; }


// }