name: Continuous Integration

# runs on
# * pushes and pull requests on the "main" (pull request only for specific paths)
# * manual trigger

on:
  push:
    branches: [ "main", "feature/*" ]

  pull_request:
    branches: [ "main", "feature/*" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./src/DataStax.AstraDB.DataApi/

      - name: Build
        run: dotnet build ./src/DataStax.AstraDB.DataApi/ --configuration Release --no-restore
